/*
 * Created on Jun 16, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package org.tolweb.tapestry;

import org.apache.tapestry.IExternalPage;
import org.apache.tapestry.IRequestCycle;
import org.apache.tapestry.html.BasePage;
import org.tolweb.dao.ImageDAO;
import org.tolweb.misc.ImageUtils;
import org.tolweb.tapestry.injections.ImageInjectable;

/**
 * @author dmandel
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
public abstract class GenerateAutogeneratedVersion extends BasePage implements IExternalPage, ImageInjectable {

    public void activateExternalPage(Object[] parameters, IRequestCycle cycle) {
        // First is the image id
        Number imgId = (Number) parameters[0];
        // Second is the height
        Number height = (Number) parameters[1];
        ImageDAO dao = getImageDAO();
        ImageUtils utils = getImageUtils();
        int closestHeight = utils.getClosestAutogeneratedVersionHeight(height.intValue());
        // if the height is invalid, use the max
        if (closestHeight <= 0) {
            closestHeight = dao.getMaxAllowedVersionHeight(imgId.intValue());
        }
        dao.getImageVersionLocationForSizedImageWithId(imgId.intValue(), closestHeight);
    }
}
