package org.tolweb.hibernate;

import java.io.Serializable;
import java.util.Date;

import org.tolweb.treegrow.main.StringUtils;

/**
 * @author lenards
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 * @hibernate.class table="MediaSurveys"
 * @hibernate.cache usage="nonstrict-read-write"
 */
public class MediaSurvey implements Serializable {

	/**
	 * serial version universal ID generated by eclipse 
	 */
	private static final long serialVersionUID = -4241512153376680718L;

	// constants defining mediaUse field 
	public static final byte BROWSING_FOR_FUN = 1; 
	public static final byte MATERIALS_FOR_OWN_PROJECTS = 2;
	public static final byte TEACHER_LIBRARIAN_CLASSROOM_MATERIALS = 4;
	public static final byte STUDENT_FOR_STUDIES = 8;
	public static final byte PARENT_LEARNING = 16;
	
	// constants defining education levels
	public static final byte KINDERGARDEN_ELEMENTARY = 1; 
	public static final byte MIDDLE_SCHOOL = 2; 
	public static final byte HIGH_SCHOOL = 4; 
	public static final byte COLLEGE_UNIVERSITY = 8; 
	public static final byte INFORMAL_EDUCATION = 16;
	
	// constants defined respondent age
	public static final byte YOUNGER_THAN_13 = 1;
	public static final byte BETWEEN_14_AND_19 = 2;
	public static final byte BETWEEN_20_AND_30 = 4;
	public static final byte BETWEEN_30_AND_60 = 8;
	public static final byte OLDER_THAN_60 = 16;
	
	private Long id = -1L, mediaId; 
	private Date timestamp; 
	private byte mediaUse; 
	private String mediaComments;
	private Long studentCount; 
	private byte educationLevel;
	private String educationComments;
	private byte respondentAge;
	private String respondentLocation;
	private String suggestions;
	
	public MediaSurvey() {
		setTimestamp(new Date());
	}
	
	public String getRespondentAgeString() {
		switch (respondentAge) {
			case YOUNGER_THAN_13:
				return "younger than 13";
			case BETWEEN_14_AND_19:
				return "between 14 and 19";
			case BETWEEN_20_AND_30:
				return "between 20 and 30";
			case BETWEEN_30_AND_60:
				return "between 30 and 60";
			case OLDER_THAN_60:
				return "older than 60";
			default: 
				return "not specified";
		}
	}

	public String getEducationLevelString() {
		String response = "";
		if (bitcmp(educationLevel, KINDERGARDEN_ELEMENTARY)) {
			response += "kindergardan/elementary school, "; 
		}
		if (bitcmp(educationLevel, MIDDLE_SCHOOL)) {
			response += "middle school, ";
		}
		if (bitcmp(educationLevel, HIGH_SCHOOL)) {
			response += "high school, ";
		}
		if (bitcmp(educationLevel, COLLEGE_UNIVERSITY)) {
			response += "college/university, ";
		}
		if (bitcmp(educationLevel, INFORMAL_EDUCATION)) {
			response += "informal education, ";
		}
		return (response.endsWith(", ")) ? response.substring(0, response.length()-2) : response;
	}
	
	public String getMediaUsageResponseString() {
		String response = "";
		if (bitcmp(mediaUse, BROWSING_FOR_FUN)) {
			response += "browsing, "; 
		} 
		if (bitcmp(mediaUse, MATERIALS_FOR_OWN_PROJECTS)) {
			response += "own projects, ";
		}
		if (bitcmp(mediaUse, TEACHER_LIBRARIAN_CLASSROOM_MATERIALS)) {
			response += "teacher/librarian, ";
		}
		if (bitcmp(mediaUse, STUDENT_FOR_STUDIES)) {
			response += "student, ";
		}
		if (bitcmp(mediaUse, PARENT_LEARNING)) {
			response += "parent, "; 
		}
		return (response.endsWith(", ")) ? response.substring(0, response.length()-2) : response;
	}

	public boolean getHasMediaComments() {
		return StringUtils.notEmpty(getMediaComments());
	}
	
	public boolean getHasEducationComments() {
		return StringUtils.notEmpty(getEducationComments());
	}
	
	public boolean getHasSuggestions() {
		return StringUtils.notEmpty(getSuggestions());
	}
	private boolean bitcmp(byte value, byte constant) {
		return (value & constant) == constant;
	}
	
	public String getMediaUsageSpecificString() {
		String response = "";
		if (bitcmp(mediaUse, BROWSING_FOR_FUN)) {
			response += "browsing for fun, "; 
		}
		if (bitcmp(mediaUse, MATERIALS_FOR_OWN_PROJECTS)) {
			response += "material for own projects, ";
		}
		if (bitcmp(mediaUse, TEACHER_LIBRARIAN_CLASSROOM_MATERIALS)) {
			response += "teacher/librarian classroom materials, ";
		}
		if (bitcmp(mediaUse, STUDENT_FOR_STUDIES)) {
			response += "student using for studies, "; 
		}
		if (bitcmp(mediaUse, PARENT_LEARNING)) {
			response += "parent using for learning w/ children, "; 
		}
		 
		return (response.endsWith(", ")) ? response.substring(0, response.length()-2) : response;
	}
	
	
	/**
	 * @hibernate.id generator-class="native" column="id" unsaved-value="-1"
	 * @return
	 */		
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}	
	/**
	 * @hibernate.property 
	 * @return
	 */	
	public String getEducationComments() {
		return educationComments;
	}
	public void setEducationComments(String educationComments) {
		this.educationComments = educationComments;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public byte getEducationLevel() {
		return educationLevel;
	}
	public void setEducationLevel(byte educationLevel) {
		this.educationLevel = educationLevel;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public String getMediaComments() {
		return mediaComments;
	}
	public void setMediaComments(String mediaComments) {
		this.mediaComments = mediaComments;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public Long getMediaId() {
		return mediaId;
	}
	public void setMediaId(Long mediaId) {
		this.mediaId = mediaId;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public byte getMediaUse() {
		return mediaUse;
	}
	public void setMediaUse(byte mediaUse) {
		this.mediaUse = mediaUse;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public byte getRespondentAge() {
		return respondentAge;
	}
	public void setRespondentAge(byte respondentAge) {
		this.respondentAge = respondentAge;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public String getRespondentLocation() {
		return respondentLocation;
	}
	public void setRespondentLocation(String respondentLocation) {
		this.respondentLocation = respondentLocation;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public Long getStudentCount() {
		return studentCount;
	}
	public void setStudentCount(Long studentCount) {
		this.studentCount = studentCount;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public String getSuggestions() {
		return suggestions;
	}
	public void setSuggestions(String suggestions) {
		this.suggestions = suggestions;
	}
	/**
	 * @hibernate.property 
	 * @return
	 */		
	public Date getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}
}
